### ISSUE TITLE
Broken in latest craft

### ISSUE THREAD

**Issue by mm-tom** [rkingon/Craft-Plugin--Inherit-Title#1]
Hi there,

When enabled, I'm seeing an error on the latest craft build (Craft Pro 2.3.2641).

```
[Error] TypeError: undefined is not an object (evaluating 'h.value')
garnish-0.1.min.js:110
```

This error prevents the ability to save an entry and disappears when I remove the inherit title field from the entry form.

**Comment by rkingon** [comment]
Craft has this built into the core now, no need for this plugin!

Just goto your sections field layout, you'll see an option to populate your title with variables from other fields :)

**Comment by mm-tom** [comment]
Amazing, thanks for the heads up - missed that!
